#define PY_SSIZE_T_CLEAN
#include "Finite_Element_Solver.h"
#include <string>
#include <iomanip>
#include <sstream>
#include <fstream>

using namespace std;

/**
* Prints the finite element solver and simulation parameters to std out
* @param total number of trajectories taken
* @param number of autoencoder frames saved per trajecotry
* @param number of actions taken by random controller during one trajectory
*/
void print_params(int total_trajectories, int samples_per_trajectory, int actions_per_trajectory)
{
	// Hyperparameters
	cout << "\nSimulation Parameters(\n";
	cout << "  (Number of Trajectories): " << total_trajectories << "\n";
	cout << "  (Samples per Trajectory): " << samples_per_trajectory << "\n";
	cout << "  (Actions per Trajectory): " << actions_per_trajectory << "\n";
	cout << ")\n";
}

/**
* Prints to stdout a readout of the current RL agent training process
* @param the current trajecotry being simulated
* @param the total number of trajectories to be simulated
*/
void print_training_info(int curr_trajectory, int total_trajectories)
{
	// Percent complete sub messege
	int percent_complete = total_trajectories>1 ? 100.0 * curr_trajectory / (total_trajectories-1) : 0.0;
	percent_complete = curr_trajectory == total_trajectories ? 100.0 : percent_complete;
	stringstream stream;
	stream << fixed << setprecision(1) << percent_complete;
	string msg1 = stream.str();
	msg1.append("% Complete");
	if (msg1.length() < 16)
	{
		msg1.append(16 - msg1.length(), ' ');
	}
	cout << msg1;
	
	// Trajectory count sub messege
	string msg2 = "";
	msg2.append("| Traj: " + to_string(curr_trajectory+1) + "/" + to_string(total_trajectories));
	if (msg2.length() < 22)
	{
		msg2.append(22 - msg2.length(), ' ');
	}
	cout << msg2;
	
	// Print return carriage
	cout << "|\r";
}

/**
* Generates random set of frames to be used to update autoencoder
* @param total number of frames generated by 1 trajectory
* @param Number of frames taken each trajectory
* @return vector of update frame indices
*/
vector<int> get_frame_indices(int tot_num_sim_steps, int samples_per_trajectory)
{
	// Create list of all frames
	vector<int> all_frames;
	for (int i = 0; i < tot_num_sim_steps; i++)
	{
		all_frames.push_back(i);
	}
	
	// Randomly shuffle list of all frames
	random_shuffle (all_frames.begin(), all_frames.end());
	
	// Populate set of update frames from shuffled list of all frames
	vector<int> update_frames;
	for (int i = 0; i < samples_per_trajectory; i++)
	{
		update_frames.push_back(all_frames[i]);
	}
	
	// Sort list of update frames
	sort (update_frames.begin(), update_frames.end());
	return update_frames;
}

/**
* Runs a set of trajectories using a random policy and simultaneously trains and autoencoder to create a reduced state representation
* @param The finite element solver object used to propogate time
* @param The total number of trajectories to be executed
* @param The number of simulation steps taken per single cycle of control application
* @param Number of trajectories to be simulated
* @param Number of training data sampled during on trajecotry
* @param Number of frames per training epoch
* @param Path to save training data to
* @return 0 on success, 1 on failure
*/
int run(Finite_Element_Solver* FES, int total_trajectories, int steps_per_control_cycle, int tot_num_sim_steps, int samples_per_trajectory, int samples_per_batch, string path)
{
	for (int curr_epoch = 0; curr_epoch < (int)floor(((double)total_trajectories*(double)samples_per_trajectory)/(double)samples_per_batch); curr_epoch++)
	{
		// Open string buffer to name data files
		stringstream stream;
	
		// Open file to save temp to
		stream << path << "/temp_data_" << curr_epoch << ".csv";
		string temp_load_name = stream.str();
		ofstream temp_data;
		temp_data.open(temp_load_name, ofstream::trunc);
		if(!temp_data.is_open())
		{
			cout << "\nFailed to open temp file\n";
			return 1;
		}
		
		// Open file to save cure to
		stream.str(string());
		stream << path << "/cure_data_" << curr_epoch << ".csv";
		string cure_load_name = stream.str();
		ofstream cure_data;
		cure_data.open (cure_load_name, ofstream::trunc);
		if(!cure_data.is_open())
		{
			cout << "\nFailed to open cure file\n";
			return 1;
		}
		
		// Run a set of episodes
		for (int curr_traj = 0; curr_traj < (int)floor((double)samples_per_batch/(double)samples_per_trajectory); curr_traj++)
		{
			// Declare simulation variables
			bool done = false;
			double action_1=0.0, action_2=0.0, action_3=0.0;
			bool apply_control, save_frame;
			int trajectory_index = 0;
			
			// Select random set of frames to be used to update autoencoder
			vector<int> frame_indices = get_frame_indices(tot_num_sim_steps, samples_per_trajectory);
			int frame_count = 0;
			int frame_index = frame_indices[frame_count];

			// User readout
			print_training_info(curr_traj+curr_epoch*(int)floor((double)samples_per_batch/(double)samples_per_trajectory), total_trajectories);

			// Save data structure
			vector<vector<double>> temp_frames[samples_per_trajectory];
			vector<vector<double>> cure_frames[samples_per_trajectory];

			// Reset environment
			FES->reset();
			
			// Simulation for loop
			while (!done)
			{
				// Determine what to run this simulation step
				apply_control = (trajectory_index % steps_per_control_cycle == 0) || (trajectory_index==0);
				save_frame = trajectory_index == frame_index;

				// Run the random controller
				if (apply_control)
				{

					// Get a random action
					action_1 = 20.0 * (2.0 * ((double)rand()/(double)RAND_MAX - 0.5));
					action_2 = 20.0 * (2.0 * ((double)rand()/(double)RAND_MAX - 0.5));
					action_3 = 20.0 * (2.0 * ((double)rand()/(double)RAND_MAX - 0.5));

					// Step the environment
					done = FES->step(action_1, action_2, action_3);
				}
				else
				{
					// Step the environment
					done = FES->step(action_1, action_2, action_3);
				}
				
				// Save data to files
				if (save_frame)
				{
					temp_frames[frame_count] = FES->get_norm_temp_mesh();
					cure_frames[frame_count] = FES->get_cure_mesh();
					
					// Update which frame is to be saved next
					frame_count++;
					if (frame_count < samples_per_trajectory)
					{
						frame_index = frame_indices[frame_count];
					}
				}

				// Update the current state and the step in episode
				trajectory_index++;

			}
			
			// Save current trajectory's frames
			for (int i = 0; i < samples_per_trajectory; i++)
			{
				for (int j = 0; j < FES->get_num_vert_length(); j++)
				{
					for(int k = 0; k < FES->get_num_vert_width(); k++)
					{
						if (k == FES->get_num_vert_width()-1)
						{
							temp_data << temp_frames[i][j][k] << "\n";
							cure_data << cure_frames[i][j][k] << "\n";
						}
						else
						{
							temp_data << temp_frames[i][j][k] << ",";
							cure_data << cure_frames[i][j][k] << ",";
						}
					}
				}
			}

			// Final user readout
			if (curr_traj+curr_epoch*(int)floor((double)samples_per_batch/(double)samples_per_trajectory) == total_trajectories - 1) { print_training_info(curr_traj+curr_epoch*(int)floor((double)samples_per_batch/(double)samples_per_trajectory), total_trajectories); }
		}

		if (temp_data.is_open()) { temp_data.close(); }
		if (cure_data.is_open()) { cure_data.close(); }
		
	}
	return 0;
}

int main()
{	
	// Training data parameters
	int total_trajectories = 5000;
	int samples_per_trajectory = 20;  // Number of temerpature and cure frames sampled per trajecotry for AE training
	int samples_per_batch = 100;      // Number of frames used per training epoch
	int actions_per_trajectory = 100; // Number of random input actions performed by controller during trajecotry
	string path = "training_data";

	// Initialize FES
	Finite_Element_Solver FES = Finite_Element_Solver(1);

	// Calculated parameters
	double control_execution_period = (FES.get_sim_duration() / ((double)actions_per_trajectory));
	int steps_per_control_cycle = (int) round(control_execution_period / FES.get_time_step());
	int tot_num_sim_steps = (int)floor(FES.get_sim_duration()/FES.get_time_step());
	
	// Print simulation parameters
	print_params(total_trajectories, samples_per_trajectory, actions_per_trajectory);
	FES.print_params();

	// Train autoencoder
	cout << "\nCollecting training data...\n";
	auto start_time = chrono::high_resolution_clock::now();
	if (run(&FES, total_trajectories, steps_per_control_cycle, tot_num_sim_steps, samples_per_trajectory, samples_per_batch, path) == 1) { return 1; }

	// Stop clock and print duration
	double duration = (double)(chrono::duration_cast<chrono::microseconds>( chrono::high_resolution_clock::now() - start_time ).count())*10e-7;
	printf("\nCollection took: %.1f seconds.\n", duration);

	// Finish
	cout << "Done!";
	return 0;
}
